project:
  type: website
  output-dir: dist
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!LICENSE.md"
    - "!Syllabus.md"
    - "!Final Project.md"
format:
  html:
    theme: 
      light: flatly
      dark: darkly
website:
  title: "Applied Gen AI"
  page-navigation: true
  sidebar:
    style: "docked"
    collapse-level: 2
    search: true
    contents:
      - text: "Course Overview"
        href: index.qmd
      - text: "---"
      - section: "Module 1: Foundations of Generative AI"
        contents:
          - text: "Slides"
            href: src/01/recap.qmd
            target: blank
          - section: "Python and Jupyter"
            contents:
            - href: src/01/python_overview.ipynb
            - href: src/01/intro_notebooks.ipynb
          - section: "Vector Embeddings"
            contents:
            - href: src/01/embeddings_using_spacy.ipynb
            - href: src/01/embeddings_using_openai.ipynb
      - section: "Module 10: Final Project"
        contents:
          - href: src/10/rubric.qmd