project:
  type: website
  output-dir: dist
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!LICENSE.md"
    - "!Syllabus.md"
    - "!Final Project.md"
website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Course Overview"
        href: index.qmd
      - section: "Module 1: Foundations of Generative AI"
        href: src/01/overview.qmd
        contents:
          - text: "Slides"
            href: src/01/recap.qmd
            target: blank
          - href: src/01/intro_notebooks.ipynb
          - href: src/01/embeddings.qmd
          - href: src/01/embeddings_using_spacy.ipynb
          - href: src/01/embeddings_using_openai.ipynb
      - section: "Module 10: Final Project"
        contents:
          - href: src/10/rubric.qmd